CREATE TABLE UserlIST(
  UserId INT PRIMARY KEY IDENTITY,
  Username VARCHAR(50) UNIQUE,
  FirstName VARCHAR(50),
  LastName VARCHAR(50),
  Email VARCHAR(100)
);

CREATE TABLE Password (
  PasswordId INT PRIMARY KEY IDENTITY,
  UserId INT FOREIGN KEY REFERENCES UserlIST(UserId) UNIQUE, 
  PasswordHash NVARCHAR(MAX) 
);